// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Tma_backend/ent/predicate"
	"Tma_backend/ent/task"
	"Tma_backend/ent/taskassignment"
	"Tma_backend/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskAssignmentQuery is the builder for querying TaskAssignment entities.
type TaskAssignmentQuery struct {
	config
	ctx        *QueryContext
	order      []taskassignment.OrderOption
	inters     []Interceptor
	predicates []predicate.TaskAssignment
	withTask   *TaskQuery
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaskAssignmentQuery builder.
func (taq *TaskAssignmentQuery) Where(ps ...predicate.TaskAssignment) *TaskAssignmentQuery {
	taq.predicates = append(taq.predicates, ps...)
	return taq
}

// Limit the number of records to be returned by this query.
func (taq *TaskAssignmentQuery) Limit(limit int) *TaskAssignmentQuery {
	taq.ctx.Limit = &limit
	return taq
}

// Offset to start from.
func (taq *TaskAssignmentQuery) Offset(offset int) *TaskAssignmentQuery {
	taq.ctx.Offset = &offset
	return taq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (taq *TaskAssignmentQuery) Unique(unique bool) *TaskAssignmentQuery {
	taq.ctx.Unique = &unique
	return taq
}

// Order specifies how the records should be ordered.
func (taq *TaskAssignmentQuery) Order(o ...taskassignment.OrderOption) *TaskAssignmentQuery {
	taq.order = append(taq.order, o...)
	return taq
}

// QueryTask chains the current query on the "task" edge.
func (taq *TaskAssignmentQuery) QueryTask() *TaskQuery {
	query := (&TaskClient{config: taq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := taq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taskassignment.Table, taskassignment.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskassignment.TaskTable, taskassignment.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(taq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (taq *TaskAssignmentQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: taq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := taq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taskassignment.Table, taskassignment.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskassignment.UserTable, taskassignment.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(taq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TaskAssignment entity from the query.
// Returns a *NotFoundError when no TaskAssignment was found.
func (taq *TaskAssignmentQuery) First(ctx context.Context) (*TaskAssignment, error) {
	nodes, err := taq.Limit(1).All(setContextOp(ctx, taq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{taskassignment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (taq *TaskAssignmentQuery) FirstX(ctx context.Context) *TaskAssignment {
	node, err := taq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaskAssignment ID from the query.
// Returns a *NotFoundError when no TaskAssignment ID was found.
func (taq *TaskAssignmentQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = taq.Limit(1).IDs(setContextOp(ctx, taq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{taskassignment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (taq *TaskAssignmentQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := taq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaskAssignment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaskAssignment entity is found.
// Returns a *NotFoundError when no TaskAssignment entities are found.
func (taq *TaskAssignmentQuery) Only(ctx context.Context) (*TaskAssignment, error) {
	nodes, err := taq.Limit(2).All(setContextOp(ctx, taq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{taskassignment.Label}
	default:
		return nil, &NotSingularError{taskassignment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (taq *TaskAssignmentQuery) OnlyX(ctx context.Context) *TaskAssignment {
	node, err := taq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaskAssignment ID in the query.
// Returns a *NotSingularError when more than one TaskAssignment ID is found.
// Returns a *NotFoundError when no entities are found.
func (taq *TaskAssignmentQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = taq.Limit(2).IDs(setContextOp(ctx, taq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{taskassignment.Label}
	default:
		err = &NotSingularError{taskassignment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (taq *TaskAssignmentQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := taq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaskAssignments.
func (taq *TaskAssignmentQuery) All(ctx context.Context) ([]*TaskAssignment, error) {
	ctx = setContextOp(ctx, taq.ctx, "All")
	if err := taq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TaskAssignment, *TaskAssignmentQuery]()
	return withInterceptors[[]*TaskAssignment](ctx, taq, qr, taq.inters)
}

// AllX is like All, but panics if an error occurs.
func (taq *TaskAssignmentQuery) AllX(ctx context.Context) []*TaskAssignment {
	nodes, err := taq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaskAssignment IDs.
func (taq *TaskAssignmentQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if taq.ctx.Unique == nil && taq.path != nil {
		taq.Unique(true)
	}
	ctx = setContextOp(ctx, taq.ctx, "IDs")
	if err = taq.Select(taskassignment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (taq *TaskAssignmentQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := taq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (taq *TaskAssignmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, taq.ctx, "Count")
	if err := taq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, taq, querierCount[*TaskAssignmentQuery](), taq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (taq *TaskAssignmentQuery) CountX(ctx context.Context) int {
	count, err := taq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (taq *TaskAssignmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, taq.ctx, "Exist")
	switch _, err := taq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (taq *TaskAssignmentQuery) ExistX(ctx context.Context) bool {
	exist, err := taq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaskAssignmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (taq *TaskAssignmentQuery) Clone() *TaskAssignmentQuery {
	if taq == nil {
		return nil
	}
	return &TaskAssignmentQuery{
		config:     taq.config,
		ctx:        taq.ctx.Clone(),
		order:      append([]taskassignment.OrderOption{}, taq.order...),
		inters:     append([]Interceptor{}, taq.inters...),
		predicates: append([]predicate.TaskAssignment{}, taq.predicates...),
		withTask:   taq.withTask.Clone(),
		withUser:   taq.withUser.Clone(),
		// clone intermediate query.
		sql:  taq.sql.Clone(),
		path: taq.path,
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (taq *TaskAssignmentQuery) WithTask(opts ...func(*TaskQuery)) *TaskAssignmentQuery {
	query := (&TaskClient{config: taq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	taq.withTask = query
	return taq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (taq *TaskAssignmentQuery) WithUser(opts ...func(*UserQuery)) *TaskAssignmentQuery {
	query := (&UserClient{config: taq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	taq.withUser = query
	return taq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TaskID uint64 `json:"task_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaskAssignment.Query().
//		GroupBy(taskassignment.FieldTaskID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (taq *TaskAssignmentQuery) GroupBy(field string, fields ...string) *TaskAssignmentGroupBy {
	taq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TaskAssignmentGroupBy{build: taq}
	grbuild.flds = &taq.ctx.Fields
	grbuild.label = taskassignment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TaskID uint64 `json:"task_id,omitempty"`
//	}
//
//	client.TaskAssignment.Query().
//		Select(taskassignment.FieldTaskID).
//		Scan(ctx, &v)
func (taq *TaskAssignmentQuery) Select(fields ...string) *TaskAssignmentSelect {
	taq.ctx.Fields = append(taq.ctx.Fields, fields...)
	sbuild := &TaskAssignmentSelect{TaskAssignmentQuery: taq}
	sbuild.label = taskassignment.Label
	sbuild.flds, sbuild.scan = &taq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TaskAssignmentSelect configured with the given aggregations.
func (taq *TaskAssignmentQuery) Aggregate(fns ...AggregateFunc) *TaskAssignmentSelect {
	return taq.Select().Aggregate(fns...)
}

func (taq *TaskAssignmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range taq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, taq); err != nil {
				return err
			}
		}
	}
	for _, f := range taq.ctx.Fields {
		if !taskassignment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if taq.path != nil {
		prev, err := taq.path(ctx)
		if err != nil {
			return err
		}
		taq.sql = prev
	}
	return nil
}

func (taq *TaskAssignmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaskAssignment, error) {
	var (
		nodes       = []*TaskAssignment{}
		_spec       = taq.querySpec()
		loadedTypes = [2]bool{
			taq.withTask != nil,
			taq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TaskAssignment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TaskAssignment{config: taq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, taq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := taq.withTask; query != nil {
		if err := taq.loadTask(ctx, query, nodes, nil,
			func(n *TaskAssignment, e *Task) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	if query := taq.withUser; query != nil {
		if err := taq.loadUser(ctx, query, nodes, nil,
			func(n *TaskAssignment, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (taq *TaskAssignmentQuery) loadTask(ctx context.Context, query *TaskQuery, nodes []*TaskAssignment, init func(*TaskAssignment), assign func(*TaskAssignment, *Task)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*TaskAssignment)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(task.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (taq *TaskAssignmentQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*TaskAssignment, init func(*TaskAssignment), assign func(*TaskAssignment, *User)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*TaskAssignment)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (taq *TaskAssignmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := taq.querySpec()
	_spec.Node.Columns = taq.ctx.Fields
	if len(taq.ctx.Fields) > 0 {
		_spec.Unique = taq.ctx.Unique != nil && *taq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, taq.driver, _spec)
}

func (taq *TaskAssignmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(taskassignment.Table, taskassignment.Columns, sqlgraph.NewFieldSpec(taskassignment.FieldID, field.TypeUint64))
	_spec.From = taq.sql
	if unique := taq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if taq.path != nil {
		_spec.Unique = true
	}
	if fields := taq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskassignment.FieldID)
		for i := range fields {
			if fields[i] != taskassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if taq.withTask != nil {
			_spec.Node.AddColumnOnce(taskassignment.FieldTaskID)
		}
		if taq.withUser != nil {
			_spec.Node.AddColumnOnce(taskassignment.FieldUserID)
		}
	}
	if ps := taq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := taq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := taq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := taq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (taq *TaskAssignmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(taq.driver.Dialect())
	t1 := builder.Table(taskassignment.Table)
	columns := taq.ctx.Fields
	if len(columns) == 0 {
		columns = taskassignment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if taq.sql != nil {
		selector = taq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if taq.ctx.Unique != nil && *taq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range taq.predicates {
		p(selector)
	}
	for _, p := range taq.order {
		p(selector)
	}
	if offset := taq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := taq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaskAssignmentGroupBy is the group-by builder for TaskAssignment entities.
type TaskAssignmentGroupBy struct {
	selector
	build *TaskAssignmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tagb *TaskAssignmentGroupBy) Aggregate(fns ...AggregateFunc) *TaskAssignmentGroupBy {
	tagb.fns = append(tagb.fns, fns...)
	return tagb
}

// Scan applies the selector query and scans the result into the given value.
func (tagb *TaskAssignmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tagb.build.ctx, "GroupBy")
	if err := tagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskAssignmentQuery, *TaskAssignmentGroupBy](ctx, tagb.build, tagb, tagb.build.inters, v)
}

func (tagb *TaskAssignmentGroupBy) sqlScan(ctx context.Context, root *TaskAssignmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tagb.fns))
	for _, fn := range tagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tagb.flds)+len(tagb.fns))
		for _, f := range *tagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TaskAssignmentSelect is the builder for selecting fields of TaskAssignment entities.
type TaskAssignmentSelect struct {
	*TaskAssignmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tas *TaskAssignmentSelect) Aggregate(fns ...AggregateFunc) *TaskAssignmentSelect {
	tas.fns = append(tas.fns, fns...)
	return tas
}

// Scan applies the selector query and scans the result into the given value.
func (tas *TaskAssignmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tas.ctx, "Select")
	if err := tas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TaskAssignmentQuery, *TaskAssignmentSelect](ctx, tas.TaskAssignmentQuery, tas, tas.inters, v)
}

func (tas *TaskAssignmentSelect) sqlScan(ctx context.Context, root *TaskAssignmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tas.fns))
	for _, fn := range tas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
